export class CONFIG_KEYS {
  static DATABASE_CLIENT = 'DATABASE_CLIENT';
  static LOG_LEVEL = 'LOG_LEVEL';
  static LOG_DATE_PATTERN = 'LOG_DATE_PATTERN';
  static LOG_DIR_NAME = 'LOG_DIR_NAME';
  static LOG_FILE_NAME = 'LOG_FILE_NAME';
  static LOG_FILE_NAME_DATE_PATTERN = 'LOG_FILE_NAME_DATE_PATTERN';
  static JWT_SECRET_KEY = 'JWT_SECRET_KEY';
  static JWT_EXPIRES_IN = 'JWT_EXPIRES_IN';
}
