export class SERVICES_NAMES {
  static QUOTE_SERVICE = 'QUOTE_SERVICE';
}

export class CONFIG_KEYS {
  static QUOTE_MS_KAFKA_HOST = 'QUOTE_MS_KAFKA_HOST';
  static QUOTE_MS_KAFKA_PORT = 'QUOTE_MS_KAFKA_PORT';
  static LOG_LEVEL = 'LOG_LEVEL';
  static LOG_DATE_PATTERN = 'LOG_DATE_PATTERN';
  static LOG_DIR_NAME = 'LOG_DIR_NAME';
  static LOG_FILE_NAME = 'LOG_FILE_NAME';
  static LOG_FILE_NAME_DATE_PATTERN = 'LOG_FILE_NAME_DATE_PATTERN';
}
