export class SERVICES_NAMES {
  static TECHNOLOGY_SERVICE = 'TECHNOLOGY_SERVICE';
}

export class CONFIG_KEYS {
  static DATABASE_TECHNOLOGY = 'DATABASE_TECHNOLOGY';
  static TECHNOLOGY_MS_KAFKA_HOST = 'TECHNOLOGY_MS_KAFKA_HOST';
  static TECHNOLOGY_MS_KAFKA_PORT = 'TECHNOLOGY_MS_KAFKA_PORT';
  static LOG_LEVEL = 'LOG_LEVEL';
  static LOG_DATE_PATTERN = 'LOG_DATE_PATTERN';
  static LOG_DIR_NAME = 'LOG_DIR_NAME';
  static LOG_FILE_NAME = 'LOG_FILE_NAME';
  static LOG_FILE_NAME_DATE_PATTERN = 'LOG_FILE_NAME_DATE_PATTERN';
}
