import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { MongooseModule } from '@nestjs/mongoose';
import { CompanyService } from './services/company/company.service';
import ConfigSchemaValidator from './config/config.schema-validator';
import { Company, CompanySchema } from './models/company.model';
import { GraphQLFederationModule } from '@nestjs/graphql';
import { join } from 'path';
import { CompanyResolver } from './resolvers/company/company.resolver';
import { ExperienceResolver } from './resolvers/experience/experience.resolver';
import { Experience, ExperienceSchema } from './models/experience.model';
import { ExperienceService } from './services/experience/experience.service';

@Module({
  imports: [
    ConfigModule.forRoot({
      envFilePath: ['apps/company/.development.env', 'apps/company/.env'],
      isGlobal: true,
      cache: true,
      validationSchema: ConfigSchemaValidator,
      validationOptions: {
        allowUnknown: true,
        abortEarly: true,
      },
      expandVariables: true,
    }),
    MongooseModule.forRootAsync({
      connectionName: 'company',
      imports: [ConfigModule],
      useFactory: async (configService: ConfigService) => {
        return {
          uri: configService.get('DATABASE_COMPANY'),
          useFindAndModify: false,
        };
      },
      inject: [ConfigService],
    }),
    MongooseModule.forRootAsync({
      connectionName: 'experience',
      imports: [ConfigModule],
      useFactory: async (configService: ConfigService) => {
        return {
          uri: configService.get('DATABASE_EXPERIENCE'),
          useFindAndModify: false,
        };
      },
      inject: [ConfigService],
    }),
    MongooseModule.forFeature(
      [{ name: Company.name, schema: CompanySchema }],
      'company',
    ),
    MongooseModule.forFeature(
      [{ name: Experience.name, schema: ExperienceSchema }],
      'experience',
    ),
    GraphQLFederationModule.forRoot({
      autoSchemaFile: join(
        process.cwd(),
        'apps/company/src/_autogenerated/schema.gql',
      ),
      playground: true,
      sortSchema: true,
      debug: true,
      buildSchemaOptions: {
        orphanedTypes: [Experience],
      },
    }),
  ],
  providers: [
    CompanyService,
    CompanyResolver,
    ExperienceService,
    ExperienceResolver,
  ],
})
export class CompanyModule {}
