export class SERVICES_NAMES {
  static COMPANY_SERVICE = 'COMPANY_SERVICE';
}

export class CONFIG_KEYS {
  static DATABASE_COMPANY = 'DATABASE_COMPANY';
  static COMPANY_MS_KAFKA_HOST = 'COMPANY_MS_KAFKA_HOST';
  static COMPANY_MS_KAFKA_PORT = 'COMPANY_MS_KAFKA_PORT';
}

export class EVENTS {
  static EXPERIENCE_CREATED = 'experience_created';
}
