export class SERVICES_NAMES {
  static COMPANY_SERVICE = 'COMPANY_SERVICE';
}

export class CONFIG_KEYS {
  static DATABASE_COMPANY = 'DATABASE_COMPANY';
  static COMPANY_MS_KAFKA_HOST = 'COMPANY_MS_KAFKA_HOST';
  static COMPANY_MS_KAFKA_PORT = 'COMPANY_MS_KAFKA_PORT';
  static LOG_LEVEL = 'LOG_LEVEL';
  static LOG_DATE_PATTERN = 'LOG_DATE_PATTERN';
  static LOG_DIR_NAME = 'LOG_DIR_NAME';
  static LOG_FILE_NAME = 'LOG_FILE_NAME';
  static LOG_FILE_NAME_DATE_PATTERN = 'LOG_FILE_NAME_DATE_PATTERN';
}

export class EVENTS {
  static EXPERIENCE_CREATED = 'experience_created';
}
