export class SERVICES_NAMES {
  static EXPERIENCE_SERVICE = 'EXPERIENCE_SERVICE';
}

export class CONFIG_KEYS {
  static DATABASE_EXPERIENCE = 'DATABASE_EXPERIENCE';
  static EXPERIENCE_MS_KAFKA_HOST = 'EXPERIENCE_MS_KAFKA_HOST';
  static EXPERIENCE_MS_KAFKA_PORT = 'EXPERIENCE_MS_KAFKA_PORT';
  static LOG_LEVEL = 'LOG_LEVEL';
  static LOG_DATE_PATTERN = 'LOG_DATE_PATTERN';
  static LOG_DIR_NAME = 'LOG_DIR_NAME';
  static LOG_FILE_NAME = 'LOG_FILE_NAME';
  static LOG_FILE_NAME_DATE_PATTERN = 'LOG_FILE_NAME_DATE_PATTERN';
}

export class EVENTS {
  static EXPERIENCE_CREATED = 'experience_created';
}
