export const PROVA = 'ciao';

export class SERVICES_NAMES {
  static EXPERIENCE_SERVICE = 'EXPERIENCE_SERVICE';
}

export class CONFIG_KEYS {
  static DATABASE_EXPERIENCE = 'DATABASE_EXPERIENCE';
  static EXPERIENCE_MS_KAFKA_HOST = 'EXPERIENCE_MS_KAFKA_HOST';
  static EXPERIENCE_MS_KAFKA_PORT = 'EXPERIENCE_MS_KAFKA_PORT';
}

export class EVENTS {
  static EXPERIENCE_CREATED = 'experience_created';
}
