import { Logger, Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { MongooseModule } from '@nestjs/mongoose';
import { ExperienceService } from './services/experience/experience.service';
import ConfigSchemaValidator from './config/config.schema-validator';
import { Experience, ExperienceSchema } from './models/experience.model';
import { GraphQLFederationModule } from '@nestjs/graphql';
import { TaskModule } from './modules/task/task.module';
import { join } from 'path';
import { ExperienceResolver } from './resolvers/experience/experience.resolver';
import { ClientsModule, Transport } from '@nestjs/microservices';
import { CONFIG_KEYS, SERVICES_NAMES } from './constants';
import { SectorModule } from './modules/sector/sector.module';
import { JwtStrategy } from '@keadex/corelib';

@Module({
  imports: [
    ConfigModule.forRoot({
      envFilePath: [
        `${
          process.env.NODE_ENV !== 'production' ? 'apps/experience/' : ''
        }.development.env`,
        `${
          process.env.NODE_ENV !== 'production' ? 'apps/experience/' : ''
        }.env`,
      ],
      isGlobal: true,
      cache: true,
      validationSchema: ConfigSchemaValidator,
      validationOptions: {
        allowUnknown: true,
        abortEarly: true,
      },
      expandVariables: true,
    }),
    MongooseModule.forRootAsync({
      useFactory: async (configService: ConfigService) => {
        return {
          uri: configService.get(CONFIG_KEYS.DATABASE_EXPERIENCE),
          useFindAndModify: false,
        };
      },
      inject: [ConfigService],
    }),
    MongooseModule.forFeature([
      { name: Experience.name, schema: ExperienceSchema },
    ]),
    GraphQLFederationModule.forRoot({
      autoSchemaFile: join(
        process.cwd(),
        'apps/experience/src/_autogenerated/schema.gql',
      ),
      playground: true,
      sortSchema: true,
      debug: true,
    }),
    ClientsModule.registerAsync([
      {
        name: SERVICES_NAMES.EXPERIENCE_SERVICE,
        useFactory: async (configService: ConfigService) => {
          return {
            transport: Transport.KAFKA,
            options: {
              client: {
                clientId: 'experience',
                brokers: [
                  configService.get(CONFIG_KEYS.EXPERIENCE_MS_KAFKA_HOST) +
                    ':' +
                    configService.get(CONFIG_KEYS.EXPERIENCE_MS_KAFKA_PORT),
                ],
              },
              consumer: {
                groupId: 'experience-consumer',
              },
            },
          };
        },
        inject: [ConfigService],
      },
    ]),
    TaskModule,
    SectorModule,
  ],
  providers: [Logger, ExperienceService, ExperienceResolver, JwtStrategy],
})
export class ExperienceModule {}
