import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { MongooseModule } from '@nestjs/mongoose';
import { SkillService } from './services/skill/skill.service';
import ConfigSchemaValidator from './config/config.schema-validator';
import { Skill, SkillSchema } from './models/skill.model';
import { GraphQLFederationModule } from '@nestjs/graphql';
import { join } from 'path';
import { SkillResolver } from './resolvers/skill/skill.resolver';
import { ClientsModule, Transport } from '@nestjs/microservices';
import { CONFIG_KEYS, SERVICES_NAMES } from './constants';

@Module({
  imports: [
    ConfigModule.forRoot({
      envFilePath: ['apps/skill/.development.env', 'apps/skill/.env'],
      isGlobal: true,
      cache: true,
      validationSchema: ConfigSchemaValidator,
      validationOptions: {
        allowUnknown: true,
        abortEarly: true,
      },
      expandVariables: true,
    }),
    MongooseModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: async (configService: ConfigService) => {
        return {
          uri: configService.get(CONFIG_KEYS.DATABASE_SKILL),
          useFindAndModify: false,
        };
      },
      inject: [ConfigService],
    }),
    MongooseModule.forFeature([{ name: Skill.name, schema: SkillSchema }]),
    GraphQLFederationModule.forRoot({
      autoSchemaFile: join(
        process.cwd(),
        'apps/skill/src/_autogenerated/schema.gql',
      ),
      playground: true,
      sortSchema: true,
      debug: true,
    }),
    ClientsModule.registerAsync([
      {
        name: SERVICES_NAMES.SKILL_SERVICE,
        useFactory: async (configService: ConfigService) => {
          return {
            transport: Transport.KAFKA,
            options: {
              client: {
                clientId: 'skill',
                brokers: [
                  configService.get(CONFIG_KEYS.SKILL_MS_KAFKA_HOST) +
                    ':' +
                    configService.get(CONFIG_KEYS.SKILL_MS_KAFKA_PORT),
                ],
              },
              consumer: {
                groupId: 'skill-consumer',
              },
            },
          };
        },
        inject: [ConfigService],
      },
    ]),
  ],
  providers: [SkillService, SkillResolver],
})
export class SkillModule {}
